Enhance commands, fix init gamelist bug, add Flask
dnh-bot/dnh-werewolf-bot pull request #124
Opened 2024-03-01 02:42 UTC by huybt22

Improve `status` command, now also showing player list with alive/dead status, role list
Fix command error when bot not init Game before
Add Flask server to keep the bot alive (use uptime monitoring)
Minor improvement for others command

2024-03-01 03:02 UTC, nitro2 reviewed
Could you explain how Flask improvement work?

2024-03-01 03:02 UTC, nitro2 commented on bot.py
> +from waitress import serve
Do we need to install any additional library to use these imports? 
If yes, please add to https://github.com/dnh-bot/dnh-werewolf-bot/blob/main/requirements.txt
If no, no action.

2024-03-01 03:51 UTC, huybt22 commented
> Could you explain how Flask improvement work?

@nitro2 In case using free deployment service, after period of inactivity, the bot will go to sleep. We use Flask to run as a web application, then manually access live website to trigger the restart but all data lost. We can ping the website to keep the bot alive using uptime monitoring services.

Ref: https://docs.render.com/free#free-web-services

2024-03-01 04:02 UTC, nitro2 submitted a review, later dismissed

2024-03-02 05:33 UTC, nitro2 commented
Could we move Flask to new file and keep bot.py stanalone?

2024-03-02 09:20 UTC, huybt22 commented
> Could we move Flask to new file and keep bot.py standalone?

Flask functions are now separated, please check.

2024-03-02 09:41 UTC, nitro2 requested changes
Please add "How to run bot on free server" in README.md section. Thanks!

2024-03-02 09:41 UTC, nitro2 commented on bot.py
> +from web import keep_alive
Please remove this

2024-03-02 09:41 UTC, nitro2 commented on requirements.txt
> +waitress==3.0.0
Since we move out these libraries from bot.py, I would prefer move these libraries to `web/requirement.txt` to minimize installing libraries for main flow.

2024-03-02 12:08 UTC, huybt22 commented
Instructions are added in README.md

2024-03-02 15:11 UTC, nitro2 commented on requirements.txt
> +Flask==3.0.2
Also move this one :D to `web/requirement.txt`

2024-03-02 15:11 UTC, nitro2 commented on bot.py
> +    # keep_alive() # Uncomment to keep the bot alive
Is it required to uncomment this to keep bot alive? Or just need to run in `web/__init__.py` ?

2024-03-02 15:25 UTC, huybt22 commented on bot.py
> +    # keep_alive() # Uncomment to keep the bot alive
Yes, it's required in order to trigger web app initialization.

2024-03-02 15:54 UTC, nitro2 approved these changes

2024-03-02 18:03 UTC, merged