Change to all player list when using index input
dnh-bot/dnh-werewolf-bot pull request #131
Opened 2024-03-05 09:23 UTC by huybt22

- Fix wrong players index input
- Now everything related to index of player should use on `all players list`
- For action curse, the dead list also includes player ID

2024-03-05 09:25 UTC, huybt22 commented
Any code block contains `get_alive_players()` should be checked carefully.

2024-03-05 12:25 UTC, nitro2 requested changes
It's better to create player_index in Player class then reuse it. Do not replace all `get_alive_players()` and `get_dead_players()` by `get_all_players()` . It can introduce newer bugs.

2024-03-05 12:25 UTC, nitro2 commented on commands/command.py
> +                        id_players = game.get_all_players()
What happens if reborn an alive player?

2024-03-05 12:39 UTC, nitro2 commented on game/__init__.py
> +            alives = self.get_all_players()
Should seer only alive players

2024-03-05 12:39 UTC, nitro2 commented on game/__init__.py
> +            alives = self.get_all_players()
Should gaurd only alive players

2024-03-09 10:02 UTC, huybt22 commented
This PR has been fixed base on the new `main` and passed checking jobs, please have a look. @nitro2

2024-03-09 14:17 UTC, neihousaigaai approved these changes

2024-03-09 14:24 UTC, nitro2 approved these changes

2024-03-09 14:24 UTC, nitro2 commented on game/text_template.py
> +    if str_value in ['False', 'off']:
nice method :D

2024-03-09 14:31 UTC, merged