Add Tanner role
dnh-bot/dnh-werewolf-bot pull request #162
Opened 2024-03-22 07:30 UTC by maidxn

2024-03-22 15:41 UTC, nitro2 submitted a review, later dismissed
Please reformat testcases (JSON files), they mix between space and tab.
Add newline at the end of JSON files (and any future file)

2024-03-23 03:52 UTC, maidxn commented
May I ask some VScode extension to format these file faster?  (Now I'm just formatting manually each file). Thank you so much

2024-03-23 04:00 UTC, neihousaigaai requested changes
Please also fix your test files name,

- Should rename `case-tanner-kill-by-...` to `case-tanner-killed-by-...`
- Fix `testcases/case-tanner-kill-by-wofl-witch-reborn-tanner-win.json` file name

2024-03-23 04:31 UTC, neihousaigaai submitted a review, later dismissed

2024-03-23 04:32 UTC, neihousaigaai approved these changes

2024-03-23 05:01 UTC, neihousaigaai approved these changes

2024-03-23 05:12 UTC, huybt22 requested changes

2024-03-23 05:12 UTC, huybt22 commented on game/__init__.py
> +                self.tanner_is_lynced = True
should be `tanner_is_lynched`

2024-03-23 05:12 UTC, huybt22 commented on game/__init__.py
> +        if self.tanner_is_lynced:
should be `tanner_is_lynched`

2024-03-23 05:12 UTC, huybt22 commented on game/__init__.py
> +        self.tanner_is_lynced = False
should be `tanner_is_lynched`

2024-03-23 05:22 UTC, huybt22 submitted a review, later dismissed

2024-03-23 05:27 UTC, neihousaigaai approved these changes

2024-03-23 05:33 UTC, huybt22 approved these changes

2024-03-23 05:38 UTC, merged