Add text when unban a not banned player
dnh-bot/dnh-werewolf-bot pull request #205
Opened 2024-04-08 18:15 UTC by maidxn

Now when unban a not banned player, it does not show error text

2024-04-09 09:08 UTC, neihousaigaai requested changes

2024-04-09 09:08 UTC, neihousaigaai commented on json/text_template.json
> +    "params": [""],
If no params required, this list **MUST** be empty.

2024-04-09 15:51 UTC, nitro2 approved these changes

2024-04-10 12:51 UTC, neihousaigaai approved these changes

2024-04-10 12:52 UTC, merged