Fix/ban and unban when reply players
dnh-bot/dnh-werewolf-bot pull request #213
Opened 2024-04-12 12:16 UTC by maidxn

Fix the mentions and the reference when ban a user

2024-04-14 09:21 UTC, huybt22 commented on commands/command.py
> +        referenced_message = await message.channel.fetch_message(reference.message_id)
is it necessary to fetch the message here?

2024-04-15 11:08 UTC, nitro2 commented on commands/command.py
> +    user = message.mentions[0] if message.mentions else params[0]
I don't understand why we use both `message.mentions[0]` and `params[0]` here.
We already had `cmd, parameters = message_parts[0], message_parts[1:]` so only check:
```python
if not params or len(params) <= 1:
  await message.reply(text_templates.generate_text("invalid_command")
  return
user = params[0]

2024-04-15 11:08 UTC, nitro2 commented on commands/command.py
> +    user = message.mentions[0] if message.mentions else params[0]
Same as above

2024-04-15 11:08 UTC, nitro2 commented on commands/command.py
> +        parameters = [reference_user_id] + parameters
What is purpose of this change? I see this change makes the parameter list become wrong and can affect to other commands.

2024-04-15 12:07 UTC, maidxn commented on commands/command.py
> +    user = message.mentions[0] if message.mentions else params[0]
I have checked it, if we use ban command as 
```!f_ban @maidxn 1000y muahaha```, we will have the mentions = [@maidxn ], and params = [@maidxn , 1000y, muahaha] 
but when we reply a message, the cmd is ```!f_ban 1000y muahaha```, mentions = None and the params =  [1000y, muahaha]

2024-04-15 12:11 UTC, maidxn commented on commands/command.py
> +        parameters = [reference_user_id] + parameters
Same as above, I think we can use this to not really mention some players, just reply the message they sent like bad words, or impolite message to ban then directly. Do you think we need this feature? If it is not neccessary, I think we can close this pr without merge it

2024-04-15 13:56 UTC, nitro2 commented on commands/command.py
> +        parameters = [reference_user_id] + parameters
Please add necessary check to prevent unexpected behavior. 
I don't think we need this feature. But `!f_ban 1000y muahaha` should not return error.

2024-04-15 15:23 UTC, nitro2 commented on commands/command.py
> +        parameters = [reference_user_id] + parameters
Yeh, I don't think this feature is necessary, I wonder the new mechanism make confused when reply with mention. 
Please just keep the parameter check part, do not add the new feature.

2024-04-16 10:17 UTC, maidxn commented on commands/command.py
> +        parameters = [reference_user_id] + parameters
Resolved it now, thank you so much for your review

2024-04-16 11:10 UTC, nitro2 requested changes

2024-04-16 11:10 UTC, nitro2 commented on commands/command.py
> +        await do_unban(message)
please re-add this, use `user = parameters[0]` instead of `user = message.mentions[0]`

2024-04-16 11:28 UTC, maidxn commented on commands/command.py
> +        await do_unban(message)
If we change this by using parameters, it will cause some errors because the parameters is just a list of strings, but the mentions will get the discord.Member object 

![image](https://github.com/dnh-bot/dnh-werewolf-bot/assets/67418054/9d00ee9e-62e8-461f-a3bc-d5747005b103)

2024-04-16 11:29 UTC, maidxn commented on commands/command.py
>      ban_reason = ' '.join(params[2:]) if len(params) > 2 else text_templates.get_word_in_language("ban_no_reason")
It will cause error for the next step below

2024-04-16 11:31 UTC, maidxn commented on commands/command.py
> +        await do_unban(message)
> If we change this by using parameters, it will cause some errors because the parameters is just a list of strings, but the mentions will get the discord.Member object
> 
> ![image](https://private-user-images.githubusercontent.com/67418054/322823546-9d00ee9e-62e8-461f-a3bc-d5747005b103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjcyOTIsIm5iZiI6MTcxMzI2Njk5MiwicGF0aCI6Ii82NzQxODA1NC8zMjI4MjM1NDYtOWQwMGVlOWUtNjJlOC00NjFmLWEzYmMtZDU3NDcwMDViMTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDExMjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MGUxZDhlYTEzNTY5NTA2YmM4Yzk2NThkZmE1YzJhZGM5NmYxYmE2Y2Y0MGZhYjk0YTAyNjI2NDU4ODYyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HKLKN9GgkXTg1dnlvT1AGT7tc6qDClmfCbfPQRIg4E4)

2024-04-16 11:43 UTC, nitro2 commented on commands/command.py
> +    user = message.mentions[0] if message.mentions else params[0]
We do not consider `!f_ban 1000y muahaha` as a valid command. This should return error.

2024-04-16 11:46 UTC, nitro2 commented on commands/command.py
> +        await do_unban(message)
Ok, accept using `user = message.mentions[0]`. Thanks.

2024-04-16 12:49 UTC, nitro2 submitted a review, later dismissed

2024-04-17 04:13 UTC, nitro2 reviewed
I recommend reverting the last commit of this PR, and use message.mention[0] for simple as you explained above. It's ok to use parameter but no need to convert it to Discord.User object. We only use the id string by the way.

2024-04-17 04:13 UTC, nitro2 commented on commands/command.py
>      if str(user.id) in BAN_DICT:
Why do we need convert the string id to Discord.User just to get the user.id again?

2024-04-19 03:54 UTC, nitro2 submitted a review, later dismissed
Refactor below texts. I'm ok with current PR.

2024-04-19 03:54 UTC, nitro2 commented on commands/command.py
> +        await message.reply("Invalid usage. Must mention player to be banned")
Please use: `text_template.generate_invalid_command_text("ban")`

2024-04-19 03:54 UTC, nitro2 commented on commands/command.py
> +        await message.reply("Invalid usage. Must mention player to be unbanned")
`text_template.generate_invalid_command_text("unban")`

2024-04-23 04:04 UTC, nitro2 approved these changes

2024-04-23 08:08 UTC, merged