Add ranking board, github gist api
dnh-bot/dnh-werewolf-bot pull request #218
Opened 2024-04-13 10:25 UTC by huybt22

resolves #185 
- Added ranking board storing in github gist
- Document will be updated later
- `gist.py` package need to be customized to work correctly, so I also put it in the source

2024-04-13 10:48 UTC, nitro2 requested changes
I want to separate process and database for rank command. The database can be local file or remote gist file. You should provide both method via an interface. I don't think normal user expect to setup new gist repo to run the bot.

2024-04-22 10:34 UTC, Stanley00 commented on config.py
> +GITHUB_GIST_TOKEN = os.getenv("GITHUB_GIST_TOKEN") if os.getenv("GITHUB_GIST_TOKEN") else None
This could be write as `GITHUB_GIST_TOKEN = os.getenv("GITHUB_GIST_TOKEN")` only

2024-04-29 14:02 UTC, nitro2 commented on bot.py
> +    valid_database = await database.verify_init()
Need a static method? @neihousaigaai @Stanley00 
Look like he needs global `database` variable because of this line

2024-05-01 11:09 UTC, huybt22 commented on .env.example
> +GITHUB_GIST_ID_URL=https://gist.github.com/*u**2*/f175ec**********817f78*******297
Commented

2024-05-01 11:09 UTC, huybt22 commented on bot.py
> +        sys.exit(1)
Done

2024-05-01 11:09 UTC, huybt22 commented on game/__init__.py
> +                change_party_victory = isinstance(players[player_id], roles.Tanner) and players[player_id].final_party == game_winner
Done

2024-05-01 11:09 UTC, huybt22 commented on game/__init__.py
> +database = Database().create_instance()
Fixed

2024-05-01 11:09 UTC, huybt22 commented on bot.py
> +    valid_database = await database.verify_init()
Fixed

2024-05-02 13:37 UTC, nitro2 commented on bot.py
> +        if not valid_database:
Use `database.get_valid()`, each guild will have different database. Eg: guild A uses local file, guild B uses gist

2024-05-02 13:44 UTC, nitro2 submitted a review, later dismissed

2024-05-03 04:10 UTC, nitro2 approved these changes

2024-05-03 04:13 UTC, merged