Add apprenticeseer role
dnh-bot/dnh-werewolf-bot pull request #248
Opened 2024-06-01 03:26 UTC by maidxn

Add ApprenticeSeer (Tiên tri tập sự)

2024-07-11 11:50 UTC, huybt22 commented
Action cmd may be better with "apseer" instead of "aseer"

2024-07-11 11:51 UTC, huybt22 commented
Will need to add apprentice seer cmd in `undo` function

2024-07-29 05:13 UTC, neihousaigaai commented
https://github.com/dnh-bot/dnh-werewolf-bot/blob/feat/add-apprenticeSeer/game/__init__.py#L1491

Inside `get_player_with_role(...)` method, the condition should be `type(...) is role`.

The `isinstance` check may cause side effect when looking for Seer (not apseer), because the apseer class is inherited from Seer class.

2024-07-29 10:52 UTC, neihousaigaai commented
Please also follow this checklist:

https://github.com/dnh-bot/dnh-werewolf-bot/issues/210#issuecomment-2255573095

2024-07-29 14:25 UTC, neihousaigaai requested changes

2024-07-29 14:25 UTC, neihousaigaai commented on game/__init__.py
> +                await self.apprenticeseer_do_end_nighttime_phase(player)
Since ApprenticeSeer class is inherited from Seer class, there is a chance that `isinstance(player, roles.ApprenticeSeer)` may not be checked. 

Should check `type(player) is roles.Seer/roles.ApprenticeSeer` instead of using `isinstance(player, roles.Seer/roles.ApprenticeSeer)`.

2024-07-30 00:46 UTC, neihousaigaai approved these changes

2024-07-30 12:43 UTC, huybt22 approved these changes

2024-07-30 14:18 UTC, merged