create !help command
dnh-bot/dnh-werewolf-bot pull request #71
Opened 2021-09-27 07:20 UTC by neihousaigaai

- create generate help text functions
- add get_character_description to characters
- edit send_embed_to_channel
- small refactor

2021-09-27 07:56 UTC, nitro2 requested changes

2021-09-27 07:56 UTC, nitro2 commented on bot.py
> +        print("Connected to server:", guild.name, "ServerID:", guild.id)
I refer the "space" here 😒

2021-09-27 07:56 UTC, nitro2 commented on commands/admin.py
> +        print("Successfully removed", user, "from", channel_name)
Please revert this change.

2021-09-27 07:56 UTC, nitro2 commented on commands/command.py
> +        return [f"`{config.BOT_PREFIX}{cmd} {player_id}`", "`{config.BOT_PREFIX}{cmd} @user`"]
```python
return [f"`{config.BOT_PREFIX}{cmd} {player_id}`", f"`{config.BOT_PREFIX}{cmd} @user`"]
```
Missing `f`

2021-09-27 07:56 UTC, nitro2 commented on commands/command.py
> +        return [f"`{config.BOT_PREFIX}{cmd}"]
Missing "\`"

2021-09-27 07:56 UTC, nitro2 commented on game/__init__.py
> +                print("Wolf:", player)
Please revert it

2021-09-27 07:56 UTC, nitro2 commented on game/__init__.py
> +            print("Error:", e)
Please revert this.

2021-09-27 07:56 UTC, nitro2 commented on game/__init__.py
> +        print("DEBUG:", num_players, num_werewolf)
Help me format this more sense. 
However I think we need to review the is_end_game() condition. Not sure it cover all cases now (Fox, Werewolf, Villager, Cupid...)

2021-09-27 07:56 UTC, nitro2 commented on game/roles/__init__.py
> +    return [Villager, Werewolf, Seer, Guard, Lycan, Superwolf, Fox, Witch]
Use set() instead.

2021-09-27 07:56 UTC, nitro2 commented on game/roles/fox.py
> +
Not sure this is a good method since we want to support multiple languages.
I think we can move these to a function in text_template.py
```python
def get_character_description(role_name_string):
    if role_name_string == "Fox":
       return "Fox - Cáo. Là kẻ ở phe thứ 3. Nếu bị Seer soi thì Fox sẽ chết."
    elif ...
```

2021-09-27 07:56 UTC, nitro2 commented on utils/logger.py
> +    pp.pprint(obj)
Please revert this.

2021-09-27 07:57 UTC, neihousaigaai commented on bot.py
> +        print("Connected to server:", guild.name, "ServerID:", guild.id)
Do you refer 2 spaces on output here?

2021-09-27 07:58 UTC, nitro2 commented
Better to move all Vietnamese strings to 1 place. So we can out source typo and content to a non-dev helper.

2021-09-27 08:00 UTC, neihousaigaai commented on commands/command.py
> +        return [f"`{config.BOT_PREFIX}{cmd} {player_id}`", "`{config.BOT_PREFIX}{cmd} @user`"]
done :+1:

2021-09-27 08:00 UTC, neihousaigaai commented on commands/command.py
> +        return [f"`{config.BOT_PREFIX}{cmd}"]
done :+1:

2021-09-27 08:04 UTC, nitro2 commented on bot.py
> +        print("Connected to server:", guild.name, "ServerID:", guild.id)
For me, they are easier to see.

2021-09-27 08:04 UTC, neihousaigaai commented on game/roles/__init__.py
> +    return [Villager, Werewolf, Seer, Guard, Lycan, Superwolf, Fox, Witch]
Maybe we will use an immutable object (e.g. tuple) here?

2021-09-27 08:07 UTC, neihousaigaai commented on game/roles/fox.py
> +
I think we should create a new role_info.json file for this case. For example:

```json
[
  {
    "role": "Fox",
    "description": {
      "vi": "Là kẻ ở phe thứ 3. Nếu bị Seer soi thì Fox sẽ chết."
    }
    "daytime_command": "vote",
    "nighttime_command": ""
  },
  ...
]
```

2021-09-27 17:30 UTC, neihousaigaai commented on game/__init__.py
> +        print("DEBUG:", num_players, num_werewolf)
How about declaring a field `character_type` in each character class?

```python
class CharacterType(Enum):
    VILLAGER = 0
    WEREWOLF = 1
    OTHERS = 2

class XXX(Character):
    def __init__(self, ...):
        self.character_type = CharacterType.VILLAGER || CharacterType.WEREWOLF || CharacterType.OTHERS
```
- `character_type` is villager if player is Villager, Seer, Guard, etc.
- `character_type` is werewolf if player is Werewolf, Superwolf, etc.
- `character_type` is others if player is Fox, Cupid, etc.

If we agree to this idea, I'll create a new issue from this.

2021-09-29 04:46 UTC, nitro2 approved these changes

2021-09-29 09:04 UTC, merged